apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
      - name: kafka-connect
        image: asia-southeast1-docker.pkg.dev/bigdata-k8s-project/bigdata-repo/kafka-connect-minio:v1
        ports:
        - containerPort: 8083 # Cổng mặc định của Kafka Connect API
        env:
        # Trỏ về cụm Kafka đang chạy trong cluster
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        # Các topic nội bộ để Kafka Connect tự quản lý trạng thái
        - name: CONNECT_GROUP_ID
          value: "minio-sink-group"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        # Định dạng dữ liệu (Đọc String, lưu dạng JSON)
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.storage.StringConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-connect"
        # ÉP REPLICATION FACTOR XUỐNG 1 (TEST DEV) để tránh lỗi khi chạy trên cluster nhỏ
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        # Truyền thông tin đăng nhập MinIO vào biến môi trường AWS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: minio-user
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: minio-pass
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
spec:
  ports:
  - port: 8083
  selector:
    app: kafka-connect