apiVersion: v1
kind: Service # Định tuyến mạng và phân giải tên miền nội bộ
metadata:
  name: my-kafka # Phân giải tên miền 
spec:
  clusterIP: None # Headless Service để không cần LoadBalancer
  ports:
  - port: 9092
    name: plaintext
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet # StatefulSet để giữ trạng thái của Zookeeper và Kafka
metadata:
  name: kafka-deployment
spec:
  serviceName: "my-kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      # Container 1: Zookeeper
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.4.0
        resources:
          requests: 
            memory: "50Mi"
          limits:
            memory: "512Mi"
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
      
      # Container 2: Kafka Broker
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        resources:
          requests: 
            memory: "100Mi"
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xms512M -Xmx512M"       
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          # Nằm chung Pod nên gọi trực tiếp qua loopback interface
          value: "localhost:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          # Expose FQDN nội bộ cho Crawler kết nối
          value: "PLAINTEXT://my-kafka:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
          subPath: data
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi # ZK chỉ lưu metadata nên cần ít
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi # Kafka lưu data thô nên cần nhiều dung lượng