apiVersion: v1
kind: Secret
metadata:
  name: weather-secrets # Tên của Secret, sẽ được tham chiếu trong Deployment của Crawler
type: Opaque
stringData:
  # Tên chìa khóa trong Secret, sẽ được tham chiếu trong Deployment của Crawler
  api-keys : "GS7H5H9LDKSFZ8MNKWPZMVG74,ZHLRVSKFWMCANAYXFK46U4SBU,QSTT859YPTN5ZKVVSHUG3ZSN4,N65FQHEAYHHD7RZPJD8K2C9XP,NFRYHME6NUPE2SKA8PRKD26YY,8B8U6KUNY633TEKVARED44YYK,Z9MQNB4GS88BMF8RNJV8ZM3UV,Q5JJ9BMQGHPLZKYXPT2AUHFBP,789DRKKC48ET8DYM3WJLWY8LE,6AD39QT8NJVXSRUZCQ6UTFVFV,STBAU2JFWAN8J674Y2UTTKY5X,ZBKMPW6GUZKN4CWRZ35DRF66R,MJMZ6G4H9B4BWBF7BZ8Y8XXBN,TG8C5LST4W7EHWKGXAWUW9EGB,U3TDNHGF4XX9BGWA9EM6MPZZQ,J7YNR4RFWF4V7URPXUAS7UYLA,45CVH5SQYJPKZQQEZ8Z4MCAZP,U3TDNHGF4XX9BGWA9EM6MPZZQ,ASF6RPXTTPRUAC5YDF43NPCS2,C5WKTWPMA53X7QYG4SRKF4Z76,53D43KJJGGW22EN2HQ8HCUD3Q,88X9Y7SGEX2AGRRKG6SMYDAEP,GLYUSYEN723XN2GRUHMM7HA7S,8JZGCSGX2SJV73J8EV9AHH3DT,JGXUEX36DVFCXY2YGZKWAB7AB,CT88PZ74RF2AJ7EW9JP5NRE84,954T5XD3K4SJ4N4N7YSLVK722,6H2WM4T9WK9MFN5375PK7KSSV,S4529ASCAR3ZKJEEFVSZLLDVM,8B8U6KUNY633TEKVARED44YYK,NXFXVBHHRQYF79ZEXHLSGS294,GVMTAQF8ELSQGM6PUAZDGBKSE,GCVZKNEFSVW7SFK3NFVNFME2E,CFADGLM7ERBQRZ98CRZVRYQGN,RYF3CU7SSMX2YGKP6T2ZE7DJ2,GVK7T5F3DNQN72LN6G3EJ6VHX,SU9SGU2FGTN32XWLY4RS4NBA6,V7EVFLAT56NSS4YUF5QQ9EF2E,5SFHTXTF97ETJJGNW3PZAL7U7,2HWMMWDMAT2J2Q7GGWFQ7TNKH"
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
type: Opaque
stringData:
  minio-user: "admin"
  minio-pass: "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  admin-user: "admin"
  admin-pass: "password123" 