apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit # Cấp quyền edit để nó có thể tạo Pod
subjects:
  - kind: ServiceAccount
    name: spark-operator-sa
    namespace: default