# --- ELASTICSEARCH SERVICE & DEPLOYMENT ---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    name: rest
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      # 1. : Mở rộng bộ nhớ ảo cho Elasticsearch 
      - name: increase-vm-max-map
        image: busybox:1.36
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true

      # 2.  Sang tên đổi chủ ổ cứng 
      - name: fix-permissions
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          runAsUser: 0 # Phải dùng quyền root (0) để đổi chủ
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      # >>> ---------------------------------------------------------------- <<<
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        resources:
          requests: 
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9200
        env:
        # Ép chạy 1 Node để tránh lỗi discovery khi chạy ES trong môi trường dev nhỏ
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
        # Giới hạn RAM của ES ở mức 512MB để không làm chết Minikube
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data # Thư mục lưu dữ liệu mặc định của ES
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
# --- MINIO SERVICE & DEPLOYMENT ---
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: api
  - port: 9001
    name: console
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        resources:
          requests: 
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        args: ["server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: storage-secrets 
              key: minio-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: storage-secrets
              key: minio-pass
        volumeMounts:
        - name: minio-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests: 
          storage: 5Gi # Cấp 5GB cho MinIO
