FROM apache/spark:3.5.0

# Chuyển sang quyền root để thao tác file
USER root


RUN curl -O https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar && \
    curl -O https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    mv *.jar /opt/spark/jars/
    

WORKDIR /opt/spark/work-dir

# Copy file code 
COPY spark_streaming.py .

# Trả lại quyền cho user spark để đảm bảo an toàn bảo mật trên K8s
USER spark